FROM plugins/base:linux-amd64

LABEL maintainer="DrizztDU <me@dtdoud.com>" \
  org.label-schema.name="Drone feishu" \
  org.label-schema.vendor="DrizztDU" \
  org.label-schema.schema-version="1.0" \
  org.opencontainers.image.source=https://github.com/DrizztDU/drone-feishu

COPY release/linux/amd64/drone-feishu /bin/

RUN apk add --no-cache tzdata

ENTRYPOINT ["/bin/drone-feishu"]
